# Copyright 2026 Syed Basim Ali
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# --- Standard library imports ---
from collections.abc import Iterator, Mapping, Sequence
from dataclasses import dataclass
from functools import lru_cache
from typing import Any, Never, TypeVar, overload
# ---------------------------------

type JsonValue = (
    str | int | float | bool | None | Sequence[JsonValue] | Mapping[str, JsonValue]
)

_P = TypeVar("_P", bound=JsonValue)
_C = TypeVar("_C", bound=float | int | bool | str)

_U = TypeVar("_U")

@lru_cache
def resolve_type_info(t_type: Any) -> tuple[Any, tuple[Any, ...]]: ...

@dataclass(frozen=True, slots=True)
class BaseKey[T]:
    value: str
    name: str = ...
    _t_type: type[T] = ...

@dataclass(frozen=True, slots=True)
class PersistenceKey(BaseKey[_P]): ...

@dataclass(frozen=True, slots=True)
class ConfigKey(BaseKey[_C]): ...

class DataDict(dict[Any, Any]):
    def __setitem__[T](self, key: BaseKey[T], value: T) -> None: ...
    def __getitem__[T](self, key: BaseKey[T]) -> T: ...
    @overload
    def get[T](self, key: BaseKey[T]) -> T | None: ...
    @overload
    def get[T, U](self, key: BaseKey[T], default: U) -> T | U: ...
    @overload
    def pop[T](self, key: BaseKey[T]) -> T: ...
    @overload
    def pop[T, U](self, key: BaseKey[T], default: U) -> T | U: ...
    def popitem(self) -> tuple[str, Any]: ...

class PersistenceData(dict[Any, Any]):
    def __setitem__(self, key: PersistenceKey[_P], value: _P) -> None: ...
    def __getitem__(self, key: PersistenceKey[_P]) -> _P: ...
    def __delitem__(self, key: PersistenceKey[_P]) -> None: ...
    @overload
    def get(self, key: PersistenceKey[_P]) -> _P | None: ...
    @overload
    def get(self, key: PersistenceKey[_P], default: _U) -> _P | _U: ...
    @overload
    def pop(self, key: PersistenceKey[_P]) -> _P: ...
    @overload
    def pop(self, key: PersistenceKey[_P], default: _U) -> _P | _U: ...
    def popitem(self) -> tuple[str, _P]: ...

class ProfileInfo(PersistenceData): ...
class HotkeyInfo(PersistenceData): ...
class OverlayInfo(PersistenceData): ...

class FrozenNamespace[K: str, V]:
    """
    A strictly immutable namespace that returns deep copies of its mutable data on access.
    """

    _data: dict[K, V]
    __slots__ = ("_data", "_name")

    def __init__(self, data: dict[K, V], name: str = ...) -> None: ...
    def __getattr__(self, name: str) -> V: ...
    def __getitem__(self, key: K) -> V: ...
    def __setattr__(self, key: Any, value: Any) -> Never: ...
    def __iter__(self) -> Iterator[tuple[K, V]]: ...
